stages:
  - build
  - release
#  - notify

variables:
    VERSION: 1.0.${CI_PIPELINE_ID}

build-code-job:
    stage: build
    script:
        - cd backend
        - mvn package -Dversion.application=${VERSION}
        - cd ../frontend
        - npm install
        - npm run build
        - cd ..
        - mkdir sausage-store-${VERSION}
        - mv backend/target/sausage-store-${VERSION}.jar sausage-store-${VERSION}/sausage-store-${VERSION}.jar
        - mv frontend/dist/frontend sausage-store-${VERSION}/public_html
    artifacts:
        paths:
            - sausage-store-${VERSION}/public_html
            - sausage-store-${VERSION}/sausage-store-${VERSION}.jar

upload-release:
  stage: release
  script:
    - cd backend
    - mvn -s settings.xml deploy -DskipTests
    - tar czvf sausage-store-${VERSION}.tar.gz sausage-store-${VERSION}
    - >
      curl -v -u "${NEXUS_REPO_USER}:${NEXUS_REPO_PASS}" --upload-file sausage-store-${VERSION}.tar.gz ${NEXUS_REPO_URL_FRONT}/sausage-store/${VERSION}/sausage-store-${VERSION}.tar.gz

#
#notify-slack: # задача с именем upload-release
#  stage: notify
#  script:
#    - > # сохранение артефакта в package registry
#      curl -X POST -H "Content-type: application/json"
#      -d "{\"text\": \"Антон Бородинский собрал ${CI_COMMIT_REF_NAME} в Gitlab.\" }" https://hooks.slack.com/services/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
