version: "3.3"

services:
  backend:
    image: gitlab.praktikum-services.ru:5050/anton-borodinskiy/sausage-store/sausage-backend:latest
    container_name: sausage-store-backend
    environment:
      # Переменные из application.properties можно заменить переменными окружения
      SPRING_DATASOURCE_USERNAME: ${PSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${PSQL_PASS}
      SPRING_DATASOURCE_URL: ${PSQL_DATASOURCE}
      SPRING_CLOUD_VAULT_TOKEN: ${VAULT_TOKEN}
      SPRING_FLYWAY_BASELINE-ON-MIGRATE: "true"
    networks:
      - sausage-store
  backend-report:
    image: gitlab.praktikum-services.ru:5050/anton-borodinskiy/sausage-store/sausage-backend-report:latest
    container_name: sausage-store-backend-report
    environment:
      DB: ${MONGO_DATA}
      SPRING_CLOUD_VAULT_TOKEN: ${VAULT_TOKEN}
    networks:
      - sausage-store
  frontend:
    image: gitlab.praktikum-services.ru:5050/anton-borodinskiy/sausage-store/sausage-frontend:latest
    container_name: sausage-store-frontend
    ports:
      - "80:80"
    networks:
      - sausage-store

networks:
  sausage-store: