version: "3.7"

services:
  backend-green:
    image: gitlab.praktikum-services.ru:5050/anton-borodinskiy/sausage-store/sausage-backend:latest
    container_name: backend-green
    environment:
      VIRTUAL_HOST: sausage-store
      VIRTUAL_PORT: 8080
      # Переменные из application.properties можно заменить переменными окружения
      SPRING_DATASOURCE_USERNAME: ${PSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${PSQL_PASS}
      SPRING_DATASOURCE_URL: "jdbc:postgresql://rc1b-5y9bn5sgesewht1l.mdb.yandexcloud.net:6432/Borodinskiy26"
      SPRING_CLOUD_VAULT_TOKEN: "hvs.CAESINsTQ_v73biUShEGBXnm10Yy15bh_D2pE6M2dwxs4lwGGh4KHGh2cy5mQkpDZWJyRVJCQm5nbDFWNUxGZ21pTTM"
      SPRING_FLYWAY_BASELINE-ON-MIGRATE: "true"
    healthcheck:
      test: curl --fail -s http://localhost:8080/actuator/health
      interval: 30s
      timeout: 10s
      start_period: 20s
      retries: 6
    networks:
      - sausage-store

  backend-blue:
    image: gitlab.praktikum-services.ru:5050/anton-borodinskiy/sausage-store/sausage-backend:latest
    container_name: backend-blue
    environment:
      VIRTUAL_HOST: sausage-store
      VIRTUAL_PORT: 8080
      # Переменные из application.properties можно заменить переменными окружения
      SPRING_DATASOURCE_USERNAME: ${PSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${PSQL_PASS}
      SPRING_DATASOURCE_URL: "jdbc:postgresql://rc1b-5y9bn5sgesewht1l.mdb.yandexcloud.net:6432/Borodinskiy26"
      SPRING_CLOUD_VAULT_TOKEN: "hvs.CAESINsTQ_v73biUShEGBXnm10Yy15bh_D2pE6M2dwxs4lwGGh4KHGh2cy5mQkpDZWJyRVJCQm5nbDFWNUxGZ21pTTM"
      SPRING_FLYWAY_BASELINE-ON-MIGRATE: "true"
    healthcheck:
      test: curl --fail -s http://localhost:8080/actuator/health
      interval: 30s
      timeout: 10s
      start_period: 20s
      retries: 6
    networks:
      - sausage-store
  backend-report:
    image: gitlab.praktikum-services.ru:5050/anton-borodinskiy/sausage-store/sausage-backend-report:latest
    container_name: sausage-backend-report
    environment:
      DB: ${DB_PYTHON}
      PORT: 5000
    ports:
      - "5000:5000"
    networks:
      - sausage-store
  frontend:
    image: gitlab.praktikum-services.ru:5050/anton-borodinskiy/sausage-store/sausage-frontend:latest
    container_name: sausage-frontend
    restart: always
    environment:
      DEFAULT_HOST: sausage-store
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - "80:80"

    networks:
      - sausage-store

networks:
  sausage-store: