version: "3.3"

services:
  backend:
    image: gitlab.praktikum-services.ru:5050/anton-borodinskiy/sausage-store/sausage-backend:latest
    container_name: sausage-backend
    environment:
      VIRTUAL_HOST: "backend"
      # Переменные из application.properties можно заменить переменными окружения
      SPRING_DATASOURCE_USERNAME: ${PSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${PSQL_PASS}
      SPRING_DATASOURCE_URL: ${PSQL_DATASOURCE}
      SPRING_CLOUD_VAULT_TOKEN: ${VAULT_TOKEN}
      SPRING_FLYWAY_BASELINE-ON-MIGRATE: "true"
    networks:
      - sausage-store
  backend-report:
    image: gitlab.praktikum-services.ru:5050/anton-borodinskiy/sausage-store/sausage-backend-report:latest
    container_name: sausage-backend-report
    environment:
      DB: ${DB_PYTHON}
      PORT: 5000
    ports:
      - "5000:5000"
    networks:
      - sausage-store
  frontend:
    image: gitlab.praktikum-services.ru:5050/anton-borodinskiy/sausage-store/sausage-frontend:latest
    container_name: sausage-frontend
    restart: always
    environment:
      DEFAULT_HOST: "backend"
      VIRTUAL_PORT: "8080"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - "80:80"

    networks:
      - sausage-store

networks:
  sausage-store: