variables:
   VERSION: 1.0.${CI_PIPELINE_ID}
   MAVEN_REPO_PATH: ./.m2/repository
   JAVA_OPTS: -XX:MaxRAMPercentage=90

stages:
   - build
   - release
   - deploy

build:
   stage: build
   script:
      - cd backend
      - mvn package -Dversion.application=${VERSION} -Dmaven.repo.local=${MAVEN_REPO_PATH}
   rules:
      - changes:
           - backend/*

release:
   stage: release
   script:
      - cd backend
      - mvn deploy -DskipTests -Dversion.application=${VERSION} -Dmaven.repo.local=${MAVEN_REPO_PATH} -s settings.xml
   rules:
      - changes:
           - backend/*
deploy:
  stage: deploy
  script:
      - ssh ${DEV_USER}@${DEV_HOST}
      # скачиваем ранее собранный артефакт с Nexus. При этом необходимо заранее
      # прописать креды от Nexus в переменные в настройке пайплайна
      -ls
      - curl -u ${NEXUS_REPO_USER}:${NEXUS_REPO_PASS} -o sausage-store-${VERSION}.jar ${NEXUS_REPO_URL_BACK}com/yandex/practicum/devops/sausage-store/${VERSION}/sausage-store-${VERSION}.jar
      # запускаем бэкенд
      - ls
      - java -jar sausage-store-${VERSION}.jar &
